import { BookOpen, Briefcase, Lightbulb, PiggyBank, UserCircle } from "lucide-react";

export const modules = [
  {
    title: "Orientación vocacional",
    description: "Descubre tu camino profesional ideal",
    icon: BookOpen,
    identifier: "678d625ce2695682ef90951b",
  },
  {
    title: "Primer empleo",
    description: "Prepárate para entrar al mundo laboral",
    icon: Briefcase,
    identifier: "678d68398e67de00d38132ee",
  },
  {
    title: "Emprendimiento",
    description: "Aprende a crear y gestionar tu propio negocio",
    icon: Lightbulb,
    identifier: "678d68398e67de00d38132ed",
  },
  {
    title: "Marca Personal",
    description: "Desarrolla tu imagen profesional única",
    icon: UserCircle,
    identifier: "678d68398e67de00d38132ec",
  },
  {
    title: "Educación financiera",
    description: "Maneja tus finanzas de manera inteligente",
    icon: PiggyBank,
    identifier: "678d68398e67de00d38132eb",
  },
];

export const funFacts = [
  "Los estudiantes que toman notas a mano tienden a aprender más que aquellos que usan dispositivos electrónicos.",
  "El 'efecto de espaciamiento' muestra que estudiar en intervalos espaciados mejora la retención a largo plazo.",
  "El aprendizaje de un nuevo idioma puede aumentar el tamaño de ciertas áreas del cerebro.",
  "El 'efecto testing' demuestra que el acto de recordar información mejora el aprendizaje más que releer el material.",
  "La técnica de 'recuperación espaciada' puede ayudar a memorizar información con mayor eficacia.",
  "La 'gamificación' en la educación puede aumentar la motivación y el compromiso de los estudiantes.",
  "El 'efecto de generación' muestra que generar una respuesta a una pregunta mejora la memoria más que simplemente leer la respuesta.",
  "La memoria de trabajo humana típicamente puede manejar 7 (más o menos 2) elementos a la vez.",
  "El aprendizaje multisensorial, que involucra más de un sentido, puede mejorar la retención de información.",
  "La 'curva del olvido' muestra que olvidamos aproximadamente el 70% de lo que aprendemos dentro de 24 horas si no lo repasamos.",
  "La técnica de 'elaboración' en el aprendizaje implica explicar y describir ideas con muchos detalles.",
  "El 'efecto de interleaving', que implica mezclar diferentes temas de estudio, puede mejorar el aprendizaje a largo plazo.",
  "La neuroplasticidad permite que nuestro cerebro forme nuevas conexiones neuronales a lo largo de toda nuestra vida.",
  "El 'efecto de concreción' muestra que la información concreta se recuerda mejor que la abstracta.",
  "La técnica de 'chunking' implica agrupar información en unidades más grandes para mejorar la memoria.",
  "El aprendizaje activo, que implica participación directa, es generalmente más efectivo que el aprendizaje pasivo.",
  "La 'carga cognitiva' se refiere a la cantidad de información que la memoria de trabajo puede manejar a la vez.",
  "El 'efecto de modalidad' sugiere que aprender a través de múltiples modalidades (visual, auditiva, etc.) puede mejorar la retención.",
  "La 'zona de desarrollo próximo' es el área entre lo que un alumno puede hacer sin ayuda y lo que puede hacer con orientación.",
  "El 'efecto de autorreferencia' muestra que relacionar la información con uno mismo mejora la memoria.",
  "La 'metacognición', o pensar sobre el pensamiento, es una habilidad crucial para el aprendizaje efectivo.",
  "El 'efecto de expectativa' muestra que nuestras expectativas pueden influir significativamente en nuestro aprendizaje y rendimiento.",
  "El 'efecto de contexto' sugiere que aprender en diferentes entornos puede mejorar la retención y la recuperación de información.",
  "La 'memoria semántica' almacena conocimientos generales y hechos sobre el mundo, independientes de experiencias personales.",
  "El 'efecto de producción' sugiere que intentar recordar información mejora la memoria más que simplemente releerla.",
  "La 'teoría de las inteligencias múltiples' propone que existen diferentes tipos de inteligencia, como la lingüística, lógica-matemática, espacial, etc.",
  "El 'efecto de atención dividida' muestra que tratar de prestar atención a múltiples fuentes de información simultáneamente puede perjudicar el aprendizaje.",
  "La 'memoria procedimental' nos permite recordar cómo hacer cosas, como andar en bicicleta o tocar un instrumento musical.",
  "El 'efecto de desplazamiento' sugiere que aprender nueva información puede hacer que olvidemos temporalmente información relacionada que ya conocíamos.",
  "La 'teoría de la carga cognitiva' sugiere que hay un límite en la cantidad de nueva información que podemos procesar a la vez.",
  "El 'efecto de niveles de procesamiento' sugiere que cuanto más profundamente procesamos la información, mejor la recordamos.",
  "La 'memoria de trabajo' es como el bloc de notas mental del cerebro, manteniendo información temporalmente para su procesamiento.",
  "El 'efecto de generación de errores' sugiere que cometer errores durante el aprendizaje puede mejorar la retención a largo plazo.",
  "La 'teoría del andamiaje' en educación implica proporcionar apoyo temporal a los estudiantes mientras desarrollan nuevas habilidades.",
  "El 'efecto de variabilidad' sugiere que variar las condiciones de práctica puede mejorar la retención y la transferencia de habilidades.",
  "La 'memoria a largo plazo' tiene una capacidad prácticamente ilimitada y puede almacenar información durante toda la vida.",
  "El 'efecto de espaciado expandido' sugiere que aumentar gradualmente los intervalos entre las sesiones de estudio puede mejorar la retención a largo plazo.",
  "La 'teoría de la autodeterminación' sugiere que la motivación intrínseca es clave para el aprendizaje efectivo y el bienestar psicológico.",
  "El 'efecto de testigo' sugiere que observar a otros realizar una tarea puede mejorar nuestro propio aprendizaje y rendimiento.",
  "La 'memoria prospectiva' nos permite recordar hacer cosas en el futuro, como tomar una medicina o asistir a una cita.",
  "El 'efecto de profundidad de procesamiento' sugiere que cuanto más significativamente procesamos la información, mejor la recordamos.",
  "La 'memoria implícita' nos permite realizar tareas sin pensar conscientemente en ellas, como atarse los cordones de los zapatos.",
  "La 'teoría de la elaboración' sugiere que relacionar nueva información con conocimientos previos mejora la comprensión y la retención.",
  "La 'memoria de trabajo visual' nos permite mantener y manipular imágenes mentales a corto plazo.",
  "El 'efecto de autogeneración' sugiere que crear nuestro propio material de estudio puede mejorar significativamente el aprendizaje.",
  "El 'efecto de espaciado' sugiere que distribuir las sesiones de estudio en el tiempo es más efectivo que el estudio intensivo.",
  "La 'memoria de trabajo auditiva' nos permite mantener y manipular información sonora a corto plazo.",
  "El 'efecto de interleaving' sugiere que alternar entre diferentes tipos de problemas durante el estudio puede mejorar el aprendizaje.",
  "La 'memoria episódica' nos permite recordar eventos específicos de nuestras vidas, incluyendo detalles contextuales.",
  "La 'teoría de la motivación ARCS' sugiere que la atención, relevancia, confianza y satisfacción son clave para motivar a los estudiantes.",
  "El método de los 'loci' es una técnica de memorización que asocia elementos a recordar con ubicaciones físicas familiares.",
  "La 'técnica Pomodoro' sugiere trabajar en intervalos de 25 minutos seguidos de descansos cortos para mejorar la productividad.",
  "El 'efecto Dunning-Kruger' muestra que las personas con poca habilidad en un área tienden a sobrestimar su competencia.",
  "La 'técnica Feynman' implica explicar un concepto en términos simples para identificar lagunas en la comprensión.",
  "El 'aprendizaje basado en proyectos' puede mejorar la retención y aplicación práctica del conocimiento.",
  "La 'técnica Cornell' para tomar notas divide la página en secciones para preguntas, notas y resumen.",
  "El 'efecto de primacía y recencia' sugiere que tendemos a recordar mejor el principio y el final de una lista.",
  "La 'técnica SQ3R' (Survey, Question, Read, Recite, Review) es un método efectivo para la comprensión de lectura.",
  "El 'aprendizaje cooperativo' puede mejorar tanto el rendimiento académico como las habilidades sociales.",
  "La 'técnica de los mapas mentales' puede ayudar a organizar y visualizar información compleja.",
  "El 'efecto de sobrecarga de opciones' sugiere que demasiadas opciones pueden dificultar la toma de decisiones.",
  "La 'regla del 80/20' o 'principio de Pareto' sugiere que el 80% de los resultados provienen del 20% del esfuerzo.",
  "El 'networking' es crucial para el desarrollo profesional y puede abrir oportunidades inesperadas.",
  "La 'marca personal' es la imagen profesional que proyectas y puede influir significativamente en tu carrera.",
  "El 'elevator pitch' es una breve presentación de 30 segundos sobre ti o tu negocio, crucial para el networking.",
  "La 'diversificación de ingresos' puede proporcionar estabilidad financiera y oportunidades de crecimiento.",
  "El 'efecto compuesto' en finanzas muestra cómo pequeñas inversiones regulares pueden crecer significativamente con el tiempo.",
  "La 'regla del 50/30/20' sugiere destinar 50% del ingreso a necesidades, 30% a deseos y 20% a ahorro e inversión.",
  "El 'sesgo de confirmación' puede llevar a buscar información que confirme nuestras creencias, ignorando evidencia contraria.",
  "La 'procrastinación' puede combatirse dividiendo tareas grandes en pasos más pequeños y manejables.",
  "La 'técnica SMART' para establecer metas sugiere que sean Específicas, Medibles, Alcanzables, Relevantes y Temporales.",
  "El 'efecto halo' puede llevar a juzgar positivamente todas las cualidades de una persona basándose en una sola característica positiva.",
  "La 'inteligencia emocional' es crucial para el éxito en el lugar de trabajo y en las relaciones personales.",
  "El 'sesgo del superviviente' puede llevar a sobrestimar las posibilidades de éxito basándose solo en ejemplos de éxito visibles.",
  "La 'técnica 5S' (Separar, Ordenar, Limpiar, Estandarizar, Mantener) puede mejorar la productividad y eficiencia.",
  "El 'principio de Parkinson' sugiere que el trabajo se expande para llenar el tiempo disponible para su realización.",
  "La 'ley de Goodhart' advierte que cuando una medida se convierte en un objetivo, deja de ser una buena medida.",
  "El 'efecto Pygmalion' sugiere que las altas expectativas de los demás pueden mejorar nuestro rendimiento.",
  "La 'técnica SWOT' (Fortalezas, Debilidades, Oportunidades, Amenazas) es útil para la planificación estratégica.",
  "El 'sesgo del costo hundido' puede llevar a continuar con un proyecto fallido debido a la inversión ya realizada.",
  "La 'técnica de los cinco porqués' puede ayudar a identificar la causa raíz de un problema.",
  "El 'principio de Peter' sugiere que las personas tienden a ascender hasta su nivel de incompetencia en una jerarquía.",
  "La 'técnica Delphi' utiliza el consenso de expertos para hacer predicciones y tomar decisiones.",
  "El 'efecto Ikea' sugiere que valoramos más los productos que hemos construido o personalizado nosotros mismos.",
  "La 'ley de Hofstadter' afirma que las tareas siempre toman más tiempo del que esperas, incluso cuando tienes en cuenta esta ley.",
  "El 'principio de Dilbert' sugiere que los empleados menos competentes son sistemáticamente trasladados donde pueden causar menos daño: la dirección.",
  "La 'técnica del análisis de escenarios' ayuda a prepararse para diferentes futuros posibles en la planificación estratégica.",
  "El 'efecto de mera exposición' sugiere que tendemos a desarrollar preferencias por cosas simplemente porque nos son familiares.",
  "La 'técnica de la pecera' es un método de discusión grupal que puede fomentar la participación y el pensamiento crítico.",
  "El 'principio de Occam' sugiere que la explicación más simple suele ser la correcta, útil en la resolución de problemas.",
  "La 'técnica de los seis sombreros para pensar' de Edward de Bono fomenta diferentes perspectivas en la toma de decisiones.",
  "El 'efecto Dunbar' sugiere que hay un límite cognitivo al número de relaciones estables que una persona puede mantener.",
  "La 'técnica PEST' (Político, Económico, Social, Tecnológico) es útil para analizar el entorno macro de un negocio.",
  "El 'principio de Hanlon' aconseja no atribuir a la maldad lo que puede explicarse adecuadamente por la estupidez.",
  "La 'técnica del árbol de decisiones' puede ayudar a visualizar y elegir entre diferentes cursos de acción.",
  "El 'efecto de anclaje' muestra cómo la primera pieza de información que recibimos influye en nuestras decisiones posteriores.",
  "La 'técnica de la lluvia de ideas' puede generar una gran cantidad de ideas creativas en poco tiempo.",
  "El 'principio de Pareto' o la 'regla del 80/20' sugiere que el 80% de los efectos provienen del 20% de las causas.",
  "La 'técnica de la escalera de inferencias' ayuda a entender cómo llegamos a conclusiones y juicios.",
  "El 'efecto de arrastre' muestra cómo las personas tienden a hacer o creer cosas porque muchos otros lo hacen.",
  "La 'técnica de los cinco whys' puede ayudar a identificar la causa raíz de un problema preguntando 'por qué' repetidamente.",
  "El 'principio KISS' (Keep It Simple, Stupid) aboga por la simplicidad en el diseño y la comunicación.",
  "La 'técnica de la matriz de Eisenhower' ayuda a priorizar tareas basándose en su urgencia e importancia.",
  "El 'efecto de dotación' muestra que las personas tienden a valorar más algo simplemente porque lo poseen.",
  "La 'técnica del análisis FODA' (Fortalezas, Oportunidades, Debilidades, Amenazas) es útil para la planificación estratégica.",
  "El 'principio de Sturgeon' afirma que '90% de todo es basura', recordándonos ser críticos y selectivos.",
  "La 'técnica de la cadena crítica' en gestión de proyectos se centra en los recursos más que en el tiempo para la planificación.",
  "El 'efecto del falso consenso' lleva a las personas a sobrestimar cuántas otras personas comparten sus creencias y comportamientos.",
  "La 'técnica de los seis sombreros para pensar' de Edward de Bono fomenta diferentes perspectivas en la resolución de problemas y toma de decisiones.",
  "El 'principio de Peter' sugiere que en una jerarquía, los empleados tienden a ascender hasta su nivel de incompetencia.",
  "La 'técnica Pomodoro' implica trabajar en intervalos de 25 minutos seguidos de descansos cortos para mejorar la productividad y el enfoque.",
  "El 'efecto Dunning-Kruger' muestra que las personas con poca habilidad en un área tienden a sobrestimar su competencia.",
  "La 'regla del 72' es una forma rápida de estimar cuánto tiempo tardará una inversión en duplicarse, dividiendo 72 por la tasa de rendimiento anual.",
  "El 'principio de Pareto' o la 'regla del 80/20' sugiere que el 80% de los resultados provienen del 20% del esfuerzo en muchas situaciones.",
  "La 'técnica SMART' para establecer metas sugiere que sean Específicas, Medibles, Alcanzables, Relevantes y Temporales.",
  "El 'efecto halo' puede llevar a juzgar positivamente todas las cualidades de una persona basándose en una sola característica positiva.",
  "La 'inteligencia emocional' es crucial para el éxito en el lugar de trabajo y en las relaciones personales, incluyendo la capacidad de reconocer y manejar emociones.",
  "El 'networking' estratégico puede abrir puertas a oportunidades profesionales y de negocio inesperadas.",
  "La 'diversificación de ingresos' puede proporcionar mayor estabilidad financiera y oportunidades de crecimiento en la carrera profesional.",
  "El 'elevator pitch' es una breve presentación de 30 segundos sobre ti o tu negocio, crucial para el networking y las oportunidades de negocio.",
  "La 'marca personal' es la imagen profesional que proyectas y puede influir significativamente en tu carrera y oportunidades laborales.",
  "La 'regla del 50/30/20' en finanzas personales sugiere destinar 50% del ingreso a necesidades, 30% a deseos y 20% a ahorro e inversión.",
  "El 'efecto compuesto' en finanzas muestra cómo pequeñas inversiones regulares pueden crecer significativamente con el tiempo debido al interés compuesto.",
  "La 'técnica de los mapas mentales' puede ayudar a organizar y visualizar información compleja, útil para la planificación y el aprendizaje.",
  "El 'principio de escasez' en marketing sugiere que las personas valoran más lo que perciben como escaso o limitado.",
  "La 'economía del don' en networking implica dar valor a otros sin expectativa inmediata de retorno, construyendo relaciones a largo plazo.",
  "El 'análisis PESTEL' (Político, Económico, Social, Tecnológico, Ecológico, Legal) es una herramienta útil para analizar el entorno macro de un negocio.",
  "La 'técnica de la escalera de retroalimentación' proporciona un marco para dar y recibir feedback constructivo en entornos profesionales.",
  "El 'efecto de recencia' sugiere que tendemos a recordar mejor la información más reciente, útil en presentaciones y entrevistas.",
  "La 'ley de Goodhart' advierte que cuando una medida se convierte en un objetivo, deja de ser una buena medida, relevante en gestión y economía.",
  "El 'principio de reciprocidad' en psicología social sugiere que las personas tienden a devolver un favor, útil en negociaciones y ventas.",
  "La 'técnica de la pecera' es un método de discusión grupal que puede fomentar la participación y el pensamiento crítico en reuniones y workshops.",
  "El 'efecto de anclaje' muestra cómo la primera pieza de información que recibimos influye en nuestras decisiones posteriores, crucial en negociaciones.",
  "La 'paradoja de la elección' sugiere que tener demasiadas opciones puede llevar a la ansiedad y la parálisis en la toma de decisiones.",
  "El 'principio de Parkinson' sugiere que el trabajo se expande para llenar el tiempo disponible para su realización, relevante en gestión del tiempo.",
  "La 'técnica GROW' (Goal, Reality, Options, Will) es un marco útil para el coaching y la resolución de problemas en entornos profesionales.",
  "El 'efecto Pygmalion' sugiere que las altas expectativas de los demás pueden mejorar nuestro rendimiento, relevante en liderazgo y educación.",
];
